name: Branches Cleanup

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up github
        uses: actions/checkout@v3
      - name: get merge branches
        run: git branch --merged | echo
        # | grep -E -v "(^\*|main|develop)"
