name: Branches Cleanup

on:
  push:
  # pull_request:
  #   types:
  #     - opened
  #   branches:
  #     - "main"
  workflow_dispatch:

jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3
      - name: get merged branches and delete them
        run: |
          git branch --merged main > merged_branches.txt
      - name: get list
        run: |
          merged_branches.txt | grep -v "main|develop" | xargs echo
