name: Node Simple CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  build:
    env:
      CI: gha
    runs-on: ubuntu-latest
    steps:
      - name: Set up github
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test_ci
