name: Todo CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Set up github
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test_ci
